name: Builds

on:
  push:
    branches: [main]
    paths:
      - "Intro Skip/**"
      - "Intro Skip.sln"
      - ".github/workflows/main.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Acquire SIRA References
        uses: ProjectSIRA/download-sira-stripped@1.0.0
        with:
          manifest: ./Intro Skip/manifest.json
          sira-server-code: ${{ secrets.SIRA_SERVER_CODE }}
      - name: Acquire Mod References
        uses: Goobwabber/download-beatmods-deps@1.2
        with:
          manifest: ./Intro Skip/manifest.json
      - name: Build
        id: Build
        env:
          FrameworkPathOverride: /usr/lib/mono/4.8-api
        run: dotnet build "Intro Skip/Intro Skip.csproj" --configuration Release
      - name: Git Status
        run: git status
      - name: Echo File Name
        run: echo $BUILDTEXT \($ASSEMBLYNAME\)
        env:
          BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
          ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Intro Skip
          path: ${{ steps.Build.outputs.artifactpath }}
